# [NB] All the modules (except the ones for testing) should probably go here,
# into this directory. May simplify dealing with symvers as well.

ccflags-y := -I$(src)

obj-m += kedr.o
kedr-objs := core.o modmap.o
